version: '3.8'

services:
  meraki-dashboard:
    build: .
    container_name: meraki-dashboard
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./config.py:/app/config.py:ro
      - ./logs:/app/logs
    networks:
      - meraki-network

  nginx:
    image: nginx:alpine
    container_name: meraki-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - meraki-dashboard
    networks:
      - meraki-network

networks:
  meraki-network:
    driver: bridge

volumes:
  logs:
